server:
  port: 8088  #服务端口号--该端口不要冲突

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/

spring:
  application:
    name: service-provider #服务名称--调用的时候根据名称来调用该服务的方法--名字绝对不能改，改了就访问不到了
